# Generated by Django 5.0.6 on 2024-06-29 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
